-- 01_setup_environment.sql
-- Purpose: Initialize Roles, Warehouses, and Databases for the Shared Analysis Zone simulation.
-- Note: In a real scenario, these would be separate accounts. We simulate this with Roles.

USE ROLE ACCOUNTADMIN;

-- 1. Create Warehouse for Analysis
CREATE OR REPLACE WAREHOUSE ANALYTICS_WH 
    WITH WAREHOUSE_SIZE = 'X-SMALL' 
    AUTO_SUSPEND = 60 
    AUTO_RESUME = TRUE 
    INITIALLY_SUSPENDED = TRUE;

-- 2. Create Simulated Roles
CREATE OR REPLACE ROLE PROVIDER_BANK;
CREATE OR REPLACE ROLE PROVIDER_INSURER;
CREATE OR REPLACE ROLE CONSUMER_ANALYST;

-- Grant Warehouse Usage
GRANT USAGE ON WAREHOUSE ANALYTICS_WH TO ROLE PROVIDER_BANK;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH TO ROLE PROVIDER_INSURER;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH TO ROLE CONSUMER_ANALYST;

-- Grant Role to current user for testing purposes
GRANT ROLE PROVIDER_BANK TO USER CURRENT_USER();
GRANT ROLE PROVIDER_INSURER TO USER CURRENT_USER();
GRANT ROLE CONSUMER_ANALYST TO USER CURRENT_USER();

-- 3. Create Databases and Schemas
-- Bank Database (Provider 1)
CREATE OR REPLACE DATABASE BANK_DB;
GRANT OWNERSHIP ON DATABASE BANK_DB TO ROLE PROVIDER_BANK;

-- Insurer Database (Provider 2)
CREATE OR REPLACE DATABASE INSURER_DB;
GRANT OWNERSHIP ON DATABASE INSURER_DB TO ROLE PROVIDER_INSURER;

-- Shared Analysis Zone (Where the "Clean Room" logic lives)
CREATE OR REPLACE DATABASE SHARED_ANALYSIS_ZONE;
GRANT OWNERSHIP ON DATABASE SHARED_ANALYSIS_ZONE TO ROLE ACCOUNTADMIN; -- Managed centrally or by a neutral party

-- Create schemas within Shared Zone for each provider to "share" secure views into
CREATE OR REPLACE SCHEMA SHARED_ANALYSIS_ZONE.CLEANROOM;
GRANT USAGE ON DATABASE SHARED_ANALYSIS_ZONE TO ROLE PROVIDER_BANK;
GRANT USAGE ON DATABASE SHARED_ANALYSIS_ZONE TO ROLE PROVIDER_INSURER;
GRANT USAGE ON DATABASE SHARED_ANALYSIS_ZONE TO ROLE CONSUMER_ANALYST;
GRANT USAGE ON SCHEMA SHARED_ANALYSIS_ZONE.CLEANROOM TO ROLE CONSUMER_ANALYST;

-- Allow Providers to create views in the Cleanroom schema (Simulating sharing)
GRANT CREATE VIEW ON SCHEMA SHARED_ANALYSIS_ZONE.CLEANROOM TO ROLE PROVIDER_BANK;
GRANT CREATE VIEW ON SCHEMA SHARED_ANALYSIS_ZONE.CLEANROOM TO ROLE PROVIDER_INSURER;

-- Grant Access to the Cleanroom Schema to Providers so they can see their own shared objects
GRANT USAGE ON SCHEMA SHARED_ANALYSIS_ZONE.CLEANROOM TO ROLE PROVIDER_BANK;
GRANT USAGE ON SCHEMA SHARED_ANALYSIS_ZONE.CLEANROOM TO ROLE PROVIDER_INSURER;

SELECT 'Environment Setup Complete' as Status;
