-- 03_setup_governance.sql
-- Purpose: Apply Snowflake Horizon governance features (Tags, Masking Policies, Row Access Policies).

USE WAREHOUSE ANALYTICS_WH;

-- ==========================================
-- 1. DEFINE TAGS (Centralized Management)
-- ==========================================
USE ROLE ACCOUNTADMIN; -- Tags often managed by a governance role or AccountAdmin
CREATE OR REPLACE DATABASE GOVERNANCE_DB;
CREATE OR REPLACE SCHEMA TAGS;

CREATE OR REPLACE TAG GOVERNANCE_DB.TAGS.PRIVACY_CATEGORY 
    ALLOWED_VALUES 'PII', 'CONFIDENTIAL', 'PUBLIC';

GRANT USAGE ON DATABASE GOVERNANCE_DB TO ROLE PROVIDER_BANK;
GRANT USAGE ON SCHEMA GOVERNANCE_DB.TAGS TO ROLE PROVIDER_BANK;
GRANT APPLY TAG ON ACCOUNT TO ROLE PROVIDER_BANK; 

GRANT USAGE ON DATABASE GOVERNANCE_DB TO ROLE PROVIDER_INSURER;
GRANT USAGE ON SCHEMA GOVERNANCE_DB.TAGS TO ROLE PROVIDER_INSURER;
GRANT APPLY TAG ON ACCOUNT TO ROLE PROVIDER_INSURER;

-- ==========================================
-- 2. CREATE MASKING POLICIES
-- ==========================================
CREATE OR REPLACE SCHEMA GOVERNANCE_DB.POLICIES;

-- String Masking Policy
CREATE OR REPLACE MASKING POLICY GOVERNANCE_DB.POLICIES.MASK_PII_STRING AS (val string) RETURNS string ->
    CASE 
        WHEN CURRENT_ROLE() IN ('PROVIDER_BANK', 'PROVIDER_INSURER', 'ACCOUNTADMIN') THEN val
        ELSE '***MASKED***'
    END;

-- Amount Masking Policy (Example: Show rounded bucket or null)
CREATE OR REPLACE MASKING POLICY GOVERNANCE_DB.POLICIES.MASK_UDF_AMOUNT AS (val number) RETURNS number ->
    CASE 
        WHEN CURRENT_ROLE() IN ('PROVIDER_BANK', 'PROVIDER_INSURER', 'ACCOUNTADMIN') THEN val
        ELSE NULL -- Consumers see NULL for raw amounts
    END;

GRANT USAGE ON DATABASE GOVERNANCE_DB TO ROLE PROVIDER_BANK;
GRANT USAGE ON SCHEMA GOVERNANCE_DB.POLICIES TO ROLE PROVIDER_BANK;
GRANT APPLY MASKING POLICY ON ACCOUNT TO ROLE PROVIDER_BANK;

GRANT USAGE ON DATABASE GOVERNANCE_DB TO ROLE PROVIDER_INSURER;
GRANT USAGE ON SCHEMA GOVERNANCE_DB.POLICIES TO ROLE PROVIDER_INSURER;
GRANT APPLY MASKING POLICY ON ACCOUNT TO ROLE PROVIDER_INSURER;

-- ==========================================
-- 3. APPLY GOVERNANCE TO BANK DATA
-- ==========================================
USE ROLE PROVIDER_BANK;

-- Apply Tags
ALTER TABLE BANK_DB.RAW.CUSTOMERS MODIFY COLUMN CUSTOMER_ID SET TAG GOVERNANCE_DB.TAGS.PRIVACY_CATEGORY = 'PII';
ALTER TABLE BANK_DB.RAW.CUSTOMERS MODIFY COLUMN INCOME_BRACKET SET TAG GOVERNANCE_DB.TAGS.PRIVACY_CATEGORY = 'CONFIDENTIAL';
ALTER TABLE BANK_DB.RAW.TRANSACTIONS MODIFY COLUMN AMOUNT SET TAG GOVERNANCE_DB.TAGS.PRIVACY_CATEGORY = 'CONFIDENTIAL';

-- Apply Masking Policies
ALTER TABLE BANK_DB.RAW.CUSTOMERS MODIFY COLUMN REGION SET MASKING POLICY GOVERNANCE_DB.POLICIES.MASK_PII_STRING;
ALTER TABLE BANK_DB.RAW.TRANSACTIONS MODIFY COLUMN AMOUNT SET MASKING POLICY GOVERNANCE_DB.POLICIES.MASK_UDF_AMOUNT;

-- ==========================================
-- 4. APPLY GOVERNANCE TO INSURER DATA
-- ==========================================
USE ROLE PROVIDER_INSURER;

-- Apply Tags
ALTER TABLE INSURER_DB.RAW.CLAIMS MODIFY COLUMN CUSTOMER_ID SET TAG GOVERNANCE_DB.TAGS.PRIVACY_CATEGORY = 'PII';

-- Apply Masking
ALTER TABLE INSURER_DB.RAW.CLAIMS MODIFY COLUMN CLAIM_AMOUNT SET MASKING POLICY GOVERNANCE_DB.POLICIES.MASK_UDF_AMOUNT;

SELECT 'Governance Setup Complete' as Status;
