-- 09_fix_permissions.sql
-- Purpose: Re-apply and verify all necessary grants for the Clean Room to function.
-- Run this if you are getting "Object does not exist" errors.

USE ROLE ACCOUNTADMIN;

-- 0. Ensure Host Access (Critical for Stored Proc execution)
-- The Procedures run as ACCOUNTADMIN (Owner), so ACCOUNTADMIN needs access to the Provider Views.
USE ROLE PROVIDER_BANK;
GRANT SELECT ON VIEW SHARED_ANALYSIS_ZONE.CLEANROOM.BANK_DATA_VIEW TO ROLE ACCOUNTADMIN;

USE ROLE PROVIDER_INSURER;
GRANT SELECT ON VIEW SHARED_ANALYSIS_ZONE.CLEANROOM.INSURER_DATA_VIEW TO ROLE ACCOUNTADMIN;

USE ROLE ACCOUNTADMIN;


-- 1. Ensure Warehouse Access
GRANT USAGE ON WAREHOUSE ANALYTICS_WH TO ROLE CONSUMER_ANALYST;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH TO ROLE PROVIDER_BANK;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH TO ROLE PROVIDER_INSURER;

-- 2. Ensure Database & Schema Usage
GRANT USAGE ON DATABASE SHARED_ANALYSIS_ZONE TO ROLE CONSUMER_ANALYST;
GRANT USAGE ON SCHEMA SHARED_ANALYSIS_ZONE.CLEANROOM TO ROLE CONSUMER_ANALYST;

GRANT USAGE ON DATABASE SHARED_ANALYSIS_ZONE TO ROLE PROVIDER_BANK;
GRANT USAGE ON SCHEMA SHARED_ANALYSIS_ZONE.CLEANROOM TO ROLE PROVIDER_BANK;

GRANT USAGE ON DATABASE SHARED_ANALYSIS_ZONE TO ROLE PROVIDER_INSURER;
GRANT USAGE ON SCHEMA SHARED_ANALYSIS_ZONE.CLEANROOM TO ROLE PROVIDER_INSURER;

-- 3. Ensure Table/Report Access
GRANT SELECT ON TABLE SHARED_ANALYSIS_ZONE.CLEANROOM.FRAUD_RISK_REPORT_HISTORY TO ROLE CONSUMER_ANALYST;

-- 4. Ensure Procedure Access 
-- (Note: Procedures must have exact signature match in grant)
GRANT USAGE ON PROCEDURE SHARED_ANALYSIS_ZONE.CLEANROOM.ANALYZE_CROSS_INDUSTRY_FRAUD(INT, INT) TO ROLE CONSUMER_ANALYST;
GRANT USAGE ON PROCEDURE SHARED_ANALYSIS_ZONE.CLEANROOM.ANALYZE_SUBSIDY_GAP() TO ROLE CONSUMER_ANALYST;

-- 5. Ensure AI Function Access
GRANT USAGE ON FUNCTION SHARED_ANALYSIS_ZONE.CLEANROOM.GENERATE_RISK_NARRATIVE(VARCHAR, NUMBER, NUMBER, NUMBER) TO ROLE CONSUMER_ANALYST;


-- 6. Verification SELECT
-- Run this block to test access
USE ROLE CONSUMER_ANALYST;
USE WAREHOUSE ANALYTICS_WH;
-- This should return empty or data, but NOT error
SELECT TOP 1 * FROM SHARED_ANALYSIS_ZONE.CLEANROOM.FRAUD_RISK_REPORT_HISTORY; 

SELECT 'Permissions Repaired. Try running 06_verify_solution.sql again.' as Status;
